package com.hacktj.studystudio

val motivationalQuotes = arrayOf(
    "Believe you can and you're halfway there. -Theodore Roosevelt",
    "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
    "The only way to do great work is to love what you do. -Steve Jobs",
    "If you can dream it, you can achieve it. -Zig Ziglar",
    "Don't let yesterday take up too much of today. -Will Rogers",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. -Norman Vincent Peale",
    "If opportunity doesn't knock, build a door. -Milton Berle",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland",
    "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
    "I have not failed. I've just found 10,000 ways that won't work. -Thomas A. Edison",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer",
    "Don't let yesterday take up too much of today. -Will Rogers",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
    "It does not matter how slowly you go as long as you do not stop. -Confucius",
    "The only way to do great work is to love what you do. -Steve Jobs",
    "If you want to achieve greatness stop asking for permission. -Anonymous",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. -Roy T. Bennett",
    "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. -Norman Vincent Peale",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward. -Martin Luther King Jr.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean",
    "Too many of us are not living our dreams because we are living our fears. -Les Brown",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. -Zig Ziglar",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
    "You are never too old to set another goal or to dream a new dream. -C.S. Lewis")